PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL DEFAULT '',
  password TEXT NOT NULL DEFAULT ''
);

INSERT OR IGNORE INTO users (id, email, password) VALUES (1, 'system', '');

CREATE TABLE IF NOT EXISTS issue_types (
  id INTEGER PRIMARY KEY,
  type TEXT,
  priority INTEGER
);

INSERT OR REPLACE INTO issue_types (id, type, priority) VALUES
(1,'ERROR_30x',1),(2,'ERROR_40x',1),(3,'ERROR_50x',1),
(4,'ERROR_DUPLICATED_TITLE',2),(5,'ERROR_DUPLICATED_DESCRIPTION',2),
(6,'ERROR_EMPTY_TITLE',2),(7,'ERROR_SHORT_TITLE',2),(8,'ERROR_LONG_TITLE',2),
(9,'ERROR_EMPTY_DESCRIPTION',2),(10,'ERROR_SHORT_DESCRIPTION',2),(11,'ERROR_LONG_DESCRIPTION',2),
(12,'ERROR_LITTLE_CONTENT',3),(13,'ERROR_IMAGES_NO_ALT',2),(14,'ERROR_REDIRECT_CHAIN',1),
(15,'ERROR_NO_H1',2),(16,'ERROR_NO_LANG',3),(17,'ERROR_HTTP_LINKS',2),(18,'ERROR_HREFLANG_RETURN',2),
(19,'ERROR_TOO_MANY_LINKS',3),(20,'ERROR_INTERNAL_NOFOLLOW',3),(21,'ERROR_EXTERNAL_WITHOUT_NOFOLLOW',3),
(22,'ERROR_CANONICALIZED_NON_CANONICAL',2),(23,'ERROR_REDIRECT_LOOP',1),(24,'ERROR_NOT_VALID_HEADINGS',2),
(25,'ERROR_HREFLANG_TO_NON_CANONICAL',2),(26,'ERROR_NOFOLLOW_INDEXABLE',2),(27,'ERROR_NO_INDEXABLE',3),
(28,'ERROR_HREFLANG_NO_INDEXABLE',3),(29,'ERROR_BLOCKED',3),(30,'ERROR_ORPHAN',3),
(31,'NO_INDEX_IN_SITEMAP',2),(32,'BLOCKED_IN_SITEMAP',2),(33,'NON_CANONICAL_IN_SITEMAP',2),
(34,'INCOMING_FOLLOW_NOFOLLOW',2),(35,'INVALID_LANG',2),(36,'HTTP_SCHEME',1),(37,'DEAD_END',3),
(38,'ERROR_CANONICALIZED_NON_INDEXABLE',3),(39,'ERROR_HREFLANG_REDIRECT',2),(40,'ERROR_CANONICAL_REDIRECT',2),
(41,'ERROR_HREFLANG_ERROR',2),(42,'ERROR_CANONICAL_ERROR',2),(43,'ERROR_MULTIPLE_CANONICAL_TAGS',2),
(44,'ERROR_RELATIVE_CANONICAL_URL',2),(45,'ERROR_HREFLANG_XDEFAULT',2),(46,'ERROR_HREFLANG_SELF_REFERENCE',2),
(47,'ERROR_HREFLANG_MISMATCHING_LANG',2),(48,'ERROR_HREFLANG_RELATIVE_URL',2),(49,'ERROR_CANONICAL_MISMATCH',2),
(50,'ERROR_MISSING_HSTS',3),(51,'ERROR_MISSING_CSP',3),(52,'ERROR_CONTENT_TYPE_OPTIONS',3),(53,'ERROR_LARGE_IMAGE',3),
(54,'ERROR_LONG_ALT_TEXT',2),(55,'ERROR_MULTIPLE_TITLES',2),(56,'ERROR_MULTIPLE_DESCRIPTIONS',2),(57,'ERROR_PAGE_DEPTH',3),
(58,'ERROR_MULTIPLE_LANG_REFERENCE',2),(59,'ERROR_DUPLICATED_CONTENT',2),(60,'ERROR_EXTERNAL_LINK_REDIRECT',3),
(61,'ERROR_EXTERNAL_LINK_BROKEN',3),(62,'ERROR_TIMEOUT',1),(63,'ERROR_UNDERSCORE_URL',3),(64,'ERROR_SLOW_TTFB',2),
(65,'ERROR_HTTP_FORM',2),(66,'ERROR_INSECURE_FORM',2),(67,'ERROR_SPACE_URL',2),(68,'ERROR_MULTIPLE_SLASHES',2),
(69,'ERROR_NOIMAGEINDEX',3),(70,'ERROR_PICTURE_MISSONG_IMG',2),(71,'ERROR_METAS_IN_BODY',2),(72,'ERROR_NOSNIPPET',3),
(73,'ERROR_IMG_SIZE_ATTR',3),(74,'ERROR_INCORRECT_MEDIA_TYPE',3),(75,'ERROR_DUPLICATED_ID',3),(76,'ERROR_MISSING_VIEWPORT',3),
(77,'ERROR_DOM_SIZE',3),(78,'ERROR_PAGINATION_LINKS',2),(79,'ERROR_LOCALHOST_LINKS',2);

CREATE TABLE IF NOT EXISTS projects (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL DEFAULT 1 REFERENCES users(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  created TEXT NOT NULL DEFAULT (datetime('now')),
  ignore_robotstxt INTEGER NOT NULL DEFAULT 0,
  follow_nofollow INTEGER NOT NULL DEFAULT 0,
  include_noindex INTEGER NOT NULL DEFAULT 0,
  crawl_sitemap INTEGER NOT NULL DEFAULT 0,
  allow_subdomains INTEGER NOT NULL DEFAULT 0,
  basic_auth INTEGER NOT NULL DEFAULT 0,
  deleting INTEGER NOT NULL DEFAULT 0,
  check_external_links INTEGER NOT NULL DEFAULT 0,
  archive INTEGER NOT NULL DEFAULT 0,
  user_agent TEXT NOT NULL DEFAULT 'Mozilla/5.0 (compatible; SEOCrawlBot/1.0)'
);

CREATE TABLE IF NOT EXISTS crawls (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  project_id INTEGER NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  start TEXT NOT NULL DEFAULT (datetime('now')),
  end TEXT,
  total_urls INTEGER NOT NULL DEFAULT 0,
  total_issues INTEGER NOT NULL DEFAULT 0,
  issues_end TEXT,
  critical_issues INTEGER NOT NULL DEFAULT 0,
  alert_issues INTEGER NOT NULL DEFAULT 0,
  warning_issues INTEGER NOT NULL DEFAULT 0,
  blocked_by_robotstxt INTEGER NOT NULL DEFAULT 0,
  noindex INTEGER NOT NULL DEFAULT 0,
  robotstxt_exists INTEGER NOT NULL DEFAULT 0,
  sitemap_exists INTEGER NOT NULL DEFAULT 0,
  sitemap_blocked INTEGER NOT NULL DEFAULT 0,
  links_internal_follow INTEGER NOT NULL DEFAULT 0,
  links_internal_nofollow INTEGER NOT NULL DEFAULT 0,
  links_external_follow INTEGER NOT NULL DEFAULT 0,
  links_external_nofollow INTEGER NOT NULL DEFAULT 0,
  links_sponsored INTEGER NOT NULL DEFAULT 0,
  links_ugc INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS pagereports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  scheme TEXT,
  redirect_url TEXT,
  refresh TEXT,
  status_code INTEGER NOT NULL,
  content_type TEXT,
  media_type TEXT,
  lang TEXT,
  title TEXT,
  description TEXT,
  robots TEXT,
  noindex INTEGER NOT NULL DEFAULT 0,
  canonical TEXT,
  h1 TEXT,
  h2 TEXT,
  words INTEGER,
  size INTEGER,
  url_hash TEXT NOT NULL DEFAULT '',
  redirect_hash TEXT,
  robotstxt_blocked INTEGER NOT NULL DEFAULT 0,
  crawled INTEGER NOT NULL DEFAULT 1,
  in_sitemap INTEGER NOT NULL DEFAULT 0,
  depth INTEGER NOT NULL DEFAULT 0,
  body_hash TEXT NOT NULL DEFAULT '',
  ttfb INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS pagereport_crawl ON pagereports(crawl_id);
CREATE INDEX IF NOT EXISTS pagereport_hash ON pagereports(url_hash);
CREATE INDEX IF NOT EXISTS idx_body_hash ON pagereports(body_hash);
CREATE INDEX IF NOT EXISTS idx_crawl_id_media_type ON pagereports(crawl_id, media_type);

CREATE TABLE IF NOT EXISTS external_links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  rel TEXT,
  text TEXT,
  nofollow INTEGER NOT NULL DEFAULT 0,
  sponsored INTEGER NOT NULL DEFAULT 0,
  ugc INTEGER NOT NULL DEFAULT 0,
  status_code INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS hreflangs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE,
  from_lang TEXT,
  to_url TEXT NOT NULL DEFAULT '',
  to_lang TEXT,
  from_hash TEXT NOT NULL DEFAULT '',
  to_hash TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS hreflangs_from_hash ON hreflangs(from_hash);
CREATE INDEX IF NOT EXISTS hreflangs_to_hash ON hreflangs(to_hash);
CREATE INDEX IF NOT EXISTS hreflangs_crawl_from_to ON hreflangs(crawl_id, from_hash, to_hash);

CREATE TABLE IF NOT EXISTS images (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  alt TEXT,
  crawl_id INTEGER REFERENCES crawls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS issues (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE,
  issue_type_id INTEGER NOT NULL REFERENCES issue_types(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS issue_crawl ON issues(crawl_id);
CREATE INDEX IF NOT EXISTS issues_issue_type ON issues(issue_type_id);

CREATE TABLE IF NOT EXISTS links (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  scheme TEXT NOT NULL,
  rel TEXT,
  text TEXT,
  url_hash TEXT NOT NULL DEFAULT '',
  nofollow INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS links_hash ON links(url_hash);
CREATE INDEX IF NOT EXISTS links_crawl ON links(crawl_id);

CREATE TABLE IF NOT EXISTS scripts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS styles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  crawl_id INTEGER REFERENCES crawls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS iframes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS audios (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  crawl_id INTEGER NOT NULL REFERENCES crawls(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  pagereport_id INTEGER NOT NULL REFERENCES pagereports(id) ON DELETE CASCADE,
  url TEXT NOT NULL DEFAULT '',
  crawl_id INTEGER REFERENCES crawls(id) ON DELETE CASCADE,
  poster TEXT NOT NULL DEFAULT ''
);
